stages:
  - test

tests:
  stage: test
  image: golang:1.24
  variables:
    GOPATH: $CI_PROJECT_DIR/.cache
  before_script:
    - mkdir -p .cache
  cache:
    paths:
      - .cache/pkg/mod/
  script:
    - go test -race -count=1 -bench . -coverprofile=coverage.out
    - mkdir coverage
    - go tool cover -html=coverage.out -o coverage/index.html
  coverage: '/coverage: \d+.\d+% of statements/'
  # artifacts:
  #   expose_as: 'Coverage report'
  #   paths:
  #     - coverage.html
  pages:
    publish: coverage
